### ISSUE TITLE
433Utils

### ISSUE THREAD

**Issue by simonkern** [windkh/flamingoswitch#1]
The code looks painfully similar to 433Utils, so I'm wondering:
Why did you delete their copyright notice? Credit where it's due...

https://github.com/ninjablocks/433Utils/blob/master/LICENSE by @ninjablocks

Their license states:

> The above copyright notice and this permission notice shall be included in all
> copies or **substantial portions of the Software**.

**Comment by windkh** [comment]
The code was not derived from this source.
The functions were named after the rcswitch library instead.

**Comment by windkh** [comment]
Added a link to https://github.com/sui77/rc-switch in readme.
