### ISSUE TITLE
sadly does not work

### ISSUE THREAD

**Issue by consolacion** [windkh/flamingoswitch#2]
I can program and control my flamingo switches via an arduino  with the aid of some codes i found on internet, those are however the codes of someone elses remote.
I had hoped to be able to scan the codes that my remote sends, so i only need to have one set of codes in the switch in order to control a switch.

Scanning my transmitter with your FlamingoReader example went well, though indeed it gave 4 codes.. and if i pressed even longer, more codes seemed to appear, so i just took the first code.
**A on**  (in fact I count much more than 4 codes)
Bin: 0010011101010111101000110110

Counter: 0 Code: 41253430 Code: 0x2757A36 Bin: 0010011101010111101000110110

 Bin: 0010011011011100110110001110

Counter: 0 Code: 41646662 Code: 0x27B7A46 Bin: 0010011110110111101001000110
Counter: 1 Code: 41568826 Code: 0x27A4A3A Bin: 0010011110100100101000111010
Counter: 2 Code: 37791194 Code: 0x240A5DA Bin: 0010010000001010010111011010
Counter: 3 Code: 40750478 Code: 0x26DCD8E Bin: 0010011011011100110110001110
Scan complete.

---
 Bin: 0010010000001010010111011010

Counter: 0 Code: 41615360 Code: 0x27B0000 Bin: 0010011110110000000000000000
Counter: 1 Code: 41646662 Code: 0x27B7A46 Bin: 0010011110110111101001000110
Counter: 2 Code: 41549824 Code: 0x27A0000 Bin: 0010011110100000000000000000
Counter: 3 Code: 37791194 Code: 0x240A5DA Bin: 0010010000001010010111011010
Scan complete.

However, upon resending those codes to my Switches, they remained dead as a doornail. Maybe it is possible to reprogram these switches by sending the code , but that wasnt the intention, i want to react them to the code i already programmed with my transmitter.
Sadly that didnt work

**Comment by windkh** [comment]
I guess there is a little pitfall which we should make sure you did not fell into.
The sniffed codes contain 28bit which is a number like 0x27B7A46 in your case. As the compiler only knows 32Bit numbers that one would result in 0x027B7A46 which is the wrong code! You have to append a trailing zero to get the right code: 0x27B7A460 <-- trailing zero here!
Could you please cross check this?

**Comment by windkh** [comment]
Another question: what type of switch do you have? Modelnumer would be great and maybe a link to where you can buy those switches....

**Comment by consolacion** [comment]
Thanks I I had the impression it was added in the program. In fact the Switch I have is aProMax 75.006.14 that is identical to the Flamingo.
I just quickly tried with the added zero. that worked perfectly for one switch, thoother switch only reacted to the OFF code and yet another only to the ON code, so I will try one of the other codes later.
I got the switch at the Dutch 'Action' chain.
This Switch is very much an enigma, I had the impression it only sent 4 codes: a Kaku2, a HomeEasy, an AC and the proper Flamingo command, but apparently the latter command changes as well. My compliments for your work

**Comment by windkh** [comment]
Have a look at my latest post here 
http://forum.arduino.cc/index.php?topic=201771.75

There is another project that managed to find out how the encryption algorithm works. There are 16 possible codes for one button...this could explain your findings.

**Comment by consolacion** [comment]
Yes had seen that yesterday night the
// (28Bit) A OFF
0x24DC206 = REC 1 OFF ROL 1
0x267C51A = REC 1 OFF ROL 3
0x25C90CE = REC 1 OFF ROL 0
0x277193A = REC 1 OFF ROL 2
wasstill a bit cryptic to me. too bad Stunteam didnt want to share his code, but was just watching http://cpp.sh/9ye4 but that needs some further studying
Anyway, have no trouble getting the switches to work with codes i found online (yours I believe) just have not found the proper codes of my transmitter yet. As said i will pick one of the other numbers and see if that works. I think you said you were planning to rewrite your library as it took too much space with all the codes hardcoded (but i know, too many other projects).
Anyway, I can get them to work, ultimately if using your codes.... no worries, I am across the border.
I have seen some people claiming to get them to work with RCswitch but i could not reproduce that.
Again, you have done great work with this enigma of a switch. I have deciphered some other brands myself but this one was hard. Not sure if there is an Action chain where you live  but they sell them here for 9.95 for 3 switches.
