### ISSUE TITLE
Request - support for the sf501 series

### ISSUE THREAD

**Issue by jeffreylanters** [windkh/flamingoswitch#3]
Thanks for this library, sadly it is not working with my set. Is there a chance I can get it to work with the sf501 series. Thanks in advance!

**Comment by windkh** [comment]
Sorry but I don‘t know the sf501 series,.. do you have a link?

**Comment by heaterC** [comment]
According to http://forum.arduino.cc/index.php?PHPSESSID=6fii7f0vh6fsmkg26aom8kli25&topic=201771.msg3330885#msg3330885 , the sf-500 is using a completely different protocol, so I assume it's the same with sf-501.

**Comment by ZillionPrey** [comment]
it would be really awesome if there is a library for the sf-501 there are quite cheap where i live

**Comment by jeffreylanters** [comment]
@DerpyDoom I managed to get it working using [this](https://github.com/hjgode/homewatch/tree/master/arduino/libraries/NewRemoteSwitch) library.
