### ISSUE TITLE
Mumbi switches do not switch on/off when sending "learned" remote code.

### ISSUE THREAD

**Issue by cgiesche** [windkh/flamingoswitch#4]
Hallo Karl-Heinz,

ich habe Deine FlamingoSwitch Library "früher" mal genutzt und wollte jetzt wieder mal mit MySensors anfangen. Ich nutze die aktuelle Version von MySensors (2.3.0) und die aktuelle Version Deiner Library.

Starte ich dein MySensors-Beispiel, sieht alles auch ersteinmal ganz gut aus: Er registriert sich am Controller und zeig die Temperatur/Luftfeuchtigkeit an. Wenn ich auf meiner Fernbedienung eine Taste (4x) drücke, sagt er auch brav, dass er was empfangen hat. Wenn ich die Codes in das Sketch eintrage und dann senden lasse, passiert an der Steckdose allerdings nichts. Reichweitenprobleme kann ich ausschließen, da Steckdose und Sender quasi direkt nebeneinander stehen. Die Hardware und verkabelung scheint auch ok zu sein, denn stöpsel ich einen Arduino mit einem alten Stand von "damals" an, schaltet sich die Steckdose ein.

Mein Log sieht in etwa so aus:
``` 
 __  __       ____
|  \/  |_   _/ ___|  ___ _ __  ___  ___  _ __ ___
| |\/| | | | \___ \ / _ \ `_ \/ __|/ _ \| `__/ __|
| |  | | |_| |___| |  __/ | | \__ \  _  | |  \__ \
|_|  |_|\__, |____/ \___|_| |_|___/\___/|_|  |___/
        |___/                      2.3.0

16 MCO:BGN:INIT REPEATER,CP=RNNRA---,VER=2.3.0
26 TSM:INIT
27 TSF:WUR:MS=0
34 TSM:INIT:TSP OK
35 TSF:SID:OK,ID=1
37 TSM:FPAR
73 TSF:MSG:SEND,1-1-255-255,s=255,c=3,t=7,pt=0,l=0,sg=0,ft=0,st=OK:
724 TSF:MSG:READ,0-0-1,s=255,c=3,t=8,pt=1,l=1,sg=0:0
730 TSF:MSG:FPAR OK,ID=0,D=1
1098 TSF:MSG:READ,4-4-1,s=255,c=3,t=8,pt=1,l=1,sg=0:1
2081 TSM:FPAR:OK
2082 TSM:ID
2083 TSM:ID:OK
2085 TSM:UPL
2088 TSF:MSG:SEND,1-1-0-0,s=255,c=3,t=24,pt=1,l=1,sg=0,ft=0,st=OK:1
2097 TSF:MSG:READ,0-0-1,s=255,c=3,t=25,pt=1,l=1,sg=0:1
2102 TSF:MSG:PONG RECV,HP=1
2104 TSM:UPL:OK
2106 TSM:READY:ID=1,PAR=0,DIS=1
2110 TSF:MSG:SEND,1-1-0-0,s=255,c=3,t=15,pt=6,l=2,sg=0,ft=0,st=OK:0100
2119 TSF:MSG:READ,0-0-1,s=255,c=3,t=15,pt=6,l=2,sg=0:0100
2126 TSF:MSG:SEND,1-1-0-0,s=255,c=0,t=18,pt=0,l=5,sg=0,ft=0,st=OK:2.3.0
2137 TSF:MSG:SEND,1-1-0-0,s=255,c=3,t=6,pt=1,l=1,sg=0,ft=0,st=OK:0
2276 TSF:MSG:READ,0-0-1,s=255,c=3,t=6,pt=0,l=1,sg=0:M
2283 TSF:MSG:SEND,1-1-0-0,s=255,c=3,t=11,pt=0,l=15,sg=0,ft=0,st=OK:Flamingo Switch
2293 TSF:MSG:SEND,1-1-0-0,s=255,c=3,t=12,pt=0,l=3,sg=0,ft=0,st=OK:2.0
2302 TSF:MSG:SEND,1-1-0-0,s=11,c=0,t=6,pt=0,l=0,sg=0,ft=0,st=OK:
2310 TSF:MSG:SEND,1-1-0-0,s=12,c=0,t=7,pt=0,l=0,sg=0,ft=0,st=OK:
2318 TSF:MSG:SEND,1-1-0-0,s=0,c=0,t=23,pt=0,l=0,sg=0,ft=0,st=OK:
2324 !MCO:SND:NODE NOT REG
2328 TSF:MSG:SEND,1-1-0-0,s=1,c=0,t=3,pt=0,l=0,sg=0,ft=0,st=OK:
Send Flamingo command 
device=0
state=1
Sending 26C675E
2335 !MCO:SND:NODE NOT REG
2343 TSF:MSG:SEND,1-1-0-0,s=2,c=0,t=3,pt=0,l=0,sg=0,ft=0,st=OK:
Send Flamingo command 
device=1
state=0
Sending 27AC9DD
2350 !MCO:SND:NODE NOT REG
2358 TSF:MSG:SEND,1-1-0-0,s=3,c=0,t=3,pt=0,l=0,sg=0,ft=0,st=OK:
Send Flamingo command 
device=2
state=1
Sending E7F4BD1
2365 !MCO:SND:NODE NOT REG
2373 TSF:MSG:SEND,1-1-0-0,s=4,c=0,t=3,pt=0,l=0,sg=0,ft=0,st=OK:
Send Flamingo command 
device=3
state=1
Sending 66A5D1A
2380 !MCO:SND:NODE NOT REG
2386 MCO:REG:REQ
2391 TSF:MSG:SEND,1-1-0-0,s=255,c=3,t=26,pt=1,l=1,sg=0,ft=0,st=OK:2
2397 TSF:MSG:READ,0-0-1,s=255,c=3,t=27,pt=1,l=1,sg=0:1
2402 MCO:PIM:NODE REG=1
2404 MCO:BGN:INIT OK,TSP=1
2759 TSF:MSG:READ,0-0-1,s=255,c=3,t=6,pt=0,l=1,sg=0:M

### Lesen der FB Codes (Einschalten)

Detected code: 2614BB6
13214 TSF:MSG:SEND,1-1-0-0,s=0,c=1,t=24,pt=5,l=4,sg=0,ft=0,st=OK:39930806
Detected code: 243DFA2
15495 !TSF:MSG:SEND,1-1-0-0,s=0,c=1,t=24,pt=5,l=4,sg=0,ft=0,st=NACK:38002594
Detected code: 257CF56
17491 TSF:MSG:SEND,1-1-0-0,s=0,c=1,t=24,pt=5,l=4,sg=0,ft=1,st=OK:39309142
Detected code: 26C675E
19906 TSF:MSG:SEND,1-1-0-0,s=0,c=1,t=24,pt=5,l=4,sg=0,ft=0,st=OK:40658782
Detected code: 26C675E
19989 TSF:MSG:SEND,1-1-0-0,s=0,c=1,t=24,pt=5,l=4,sg=0,ft=0,st=OK:40658782


T: 27.00 C
62409 TSF:MSG:SEND,1-1-0-0,s=11,c=1,t=0,pt=7,l=5,sg=0,ft=0,st=OK:27.0
H: 43.00 %
62418 TSF:MSG:SEND,1-1-0-0,s=12,c=1,t=1,pt=7,l=5,sg=0,ft=0,st=OK:43.0

## Ausschalten

87950 TSF:MSG:READ,0-0-1,s=1,c=1,t=2,pt=0,l=1,sg=0:1
Incoming change for switch:1, value: 1
Send Flamingo command 
device=0
state=1
Sending 257CF56
87960 TSF:MSG:SEND,1-1-0-0,s=1,c=1,t=2,pt=1,l=1,sg=0,ft=0,st=OK:1

## Einschalten

99009 TSF:MSG:READ,0-0-1,s=1,c=1,t=2,pt=0,l=1,sg=0:0
Incoming change for switch:1, value: 0
Send Flamingo command 
device=0
state=0
Sending 243508E
99019 TSF:MSG:SEND,1-1-0-0,s=1,c=1,t=2,pt=1,l=1,sg=0,ft=0,st=OK:0
```

Die "gelernten" Codes habe ich einfach in der Form 0x[DetectedCode] in die Config eingetragen:

```
{0x26E419A, 0x243508E, 0x2449D86, 0x26FFFFA}, // (28Bit) A OFF
{0x26C675E, 0x2614BB6, 0x243DFA2, 0x257CF56} // (28Bit) A ON
```

Ich würde mich freuen, wenn Du vielleicht eine Lösung parat hättest. Meine Selbsthilfe-Skills sind bei diesem Thema äußerst begrenzt :)

Viele Grüße
Christoph

**Comment by windkh** [comment]
Hi Christoph,
Ich bin gerade unterwegs und kann es nicht genau nachvollziehen. Irgendwann aber habe ich die 28Bit anders auf duie 32Bit verteilt.
Ohne dass ich es nun exakt sagen kann: probier mal die 28Bit rechtsbündig statt linksbündig einzusetzen
0x1234567 —> 0x01234567

Ich kümmer mich sobald ich wieder daheim bin, habe aber selbst MySensors 2.0 damit laufen.... es geht also.
Gr kh

Gesendet mit der WEB.DE iPad App

Am 07.07.18 um 16:59 schrieb Christoph Giesche

**Comment by cgiesche** [comment]
Hallo Karl-Heinz,

vielen Dank für die schnelle Rückmeldung.

Ich habe die Hardware jetzt zwei mal parallel aufgebaut, um auszuschließen, dass ich irgendwas verbastelt habe.

Beide empfangen und loggen die gleichen Fernbedienungs-Codes. Beide behaupten auch die korrekten Codes zu senden, aber weder die Steckdose, noch der jeweils andere Sensor bekommen davon etwas mit.

Der History Deines Sketches nach zu urteilen waren die Codes mal im der Form `0x[1234567]0` und jetzt als `0x[1234567]` angegeben. Um sicher zu gehen, hab ich alle 3 Varianten ausprobiert:

```
        {
            {0x26E419A, 0x243508E, 0x2449D86, 0x26FFFFA}, // (28Bit) A OFF
            {0x26C675E, 0x2614BB6, 0x243DFA2, 0x257CF56}  // (28Bit) A ON
        },
        {
            {0x026E419A, 0x0243508E, 0x02449D86, 0x026FFFFA}, // (28Bit) A OFF
            {0x026C675E, 0x02614BB6, 0x0243DFA2, 0x0257CF56}  // (28Bit) A ON
        },
        {
            {0x26E419A0, 0x243508E0, 0x2449D860, 0x26FFFFA0}, // (28Bit) A OFF
            {0x26C675E0, 0x2614BB60, 0x243DFA20, 0x257CF560}  // (28Bit) A ON
        },
```
Wobei Variante 1 und 2 identisch sind, wenn ich das richtig sehe. Ist aber auch egal: Es funktioniert keine davon.

Ich habe gesehen, dass irgendwas mit Encryption dazugekommen ist. Kann es damit zusammenhängen?

PS. Es eilt nicht. Bitte keine Umstände wegen mir :)

**Comment by windkh** [comment]
Das ist der sketch den ich nutze
https://github.com/windkh/mysensors/blob/master/FlamingoSwitchSensor/FlamingoSwitchSensor.ino

Kannst auch mit dem timing von 300ms experimentieren 300-330... 

Vg kh

Gesendet mit der WEB.DE iPad App

Am 07.07.18 um 22:35 schrieb Christoph Giesche

**Comment by cgiesche** [comment]
Tja, so einfach kann das Leben sein: Ich hab das Timing auf 300 reduziert und zack sitze ich im Dunkeln (im positiven Sinne, da mir der Sender das Licht ausgeschaltet hat).

Vielen Dank für Deine Unterstützung!

--

Reducing the PULSE_LENGTH in FlamingoSwitch.cpp (back) to 300 made the sender work again with my mumbi switches.
